name: expense_tracker
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  firebase_messaging: ^14.7.21
  shared_preferences: ^2.0.0
  intl: ^0.18.1
  flutter_datetime_picker_plus: ^2.1.0
  firebase_core: ^2.27.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.3
  
  

dev_dependencies:
  flutter_lints: ^2.0.0 
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  hive_generator: ^1.1.3
flutter:
  uses-material-design: true
  assets:
    - images/

